export enum Path {
  main = '/',
  home = 'home',
  phones = 'phones',
  tablets = 'tablets',
  accessories = 'accessories',
  phonesId = 'phones/:id',
  tabletsId = 'tablets/:id',
  accessoriesId = 'accessories/:id',
  cart = 'cart',
  favourites = 'favourites',
  notFound = '*',
  dashboard = 'dashboard',
  register = 'register',
  login = '/login',
  forgotPassword = '/forgot-password',
  contacts = 'contacts',
  rights = 'rights',
}
